# config.yaml

# List of target URLs to request
targets:
  - "https://nowsecure.nl/" # A good site to test TLS fingerprints
  - "https://www.viagogo.co.uk/Concert-Tickets/Rock-and-Pop/Sting-Tickets/E-157332132"
  - "https://www.stubhub.com/stardew-valley-denver-tickets-9-13-2025/event/156264784"

# List of proxies in user:pass@ip:port or ip:port format
proxies:
  - "user1:pass1@1.2.3.4:8080"
  - "user2:pass2@5.6.7.8:9000"
  # Add your actual proxies here

# Request settings
settings:
  # Total number of successful requests to attempt
  request_count: 10
  # Max retries for a single request if it's blocked or fails
  max_retries: 3
  # TLS Profile: "chrome", "firefox", "safari", or "random"
  tls_profile: "random"
  # Enable cookie handling (recommended for stealth)
  use_cookies: true
  # Delay range between requests in milliseconds (human-like timing)
  delay_ms:
    min: 2000
    max: 8000
  # Custom headers (optional - will override defaults)
  custom_headers: